# Generated by Django 2.0.1 on 2018-01-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PortfolioItem',
            new_name='Portfolio',
        ),
    ]
